//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceCraft.Client.Locales {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VoiceCraft.Client.Locales.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings.General", resourceCulture);
            }
        }
        
        public static string Home_Settings {
            get {
                return ResourceManager.GetString("Home.Settings", resourceCulture);
            }
        }
        
        public static string Home_Servers {
            get {
                return ResourceManager.GetString("Home.Servers", resourceCulture);
            }
        }
        
        public static string Home_Credits {
            get {
                return ResourceManager.GetString("Home.Credits", resourceCulture);
            }
        }
        
        public static string Home_AddServer {
            get {
                return ResourceManager.GetString("Home.AddServer", resourceCulture);
            }
        }
        
        public static string Settings_General_Language {
            get {
                return ResourceManager.GetString("Settings.General.Language", resourceCulture);
            }
        }
        
        public static string Settings_General_Theme {
            get {
                return ResourceManager.GetString("Settings.General.Theme", resourceCulture);
            }
        }
        
        public static string Settings_General_BackgroundImage {
            get {
                return ResourceManager.GetString("Settings.General.BackgroundImage", resourceCulture);
            }
        }
        
        public static string Settings_General_NotificationDismiss {
            get {
                return ResourceManager.GetString("Settings.General.NotificationDismiss", resourceCulture);
            }
        }
        
        public static string Settings_General_HideServerAddresses {
            get {
                return ResourceManager.GetString("Settings.General.HideServerAddresses", resourceCulture);
            }
        }
        
        public static string Settings_General_DisableNotifications {
            get {
                return ResourceManager.GetString("Settings.General.DisableNotifications", resourceCulture);
            }
        }
        
        public static string Settings_Audio {
            get {
                return ResourceManager.GetString("Settings.Audio", resourceCulture);
            }
        }
        
        public static string Android_AudioPlayer_Exception_Encoding {
            get {
                return ResourceManager.GetString("Android.AudioPlayer.Exception.Encoding", resourceCulture);
            }
        }
        
        public static string Android_AudioPlayer_Exception_Format {
            get {
                return ResourceManager.GetString("Android.AudioPlayer.Exception.Format", resourceCulture);
            }
        }
        
        public static string Android_AudioPlayer_Exception_ChannelMask {
            get {
                return ResourceManager.GetString("Android.AudioPlayer.Exception.ChannelMask", resourceCulture);
            }
        }
        
        public static string Android_AudioPlayer_Exception_CreateAudioTrack {
            get {
                return ResourceManager.GetString("Android.AudioPlayer.Exception.CreateAudioTrack", resourceCulture);
            }
        }
        
        public static string Android_AudioPlayer_Exception_Write {
            get {
                return ResourceManager.GetString("Android.AudioPlayer.Exception.Write", resourceCulture);
            }
        }
        
        public static string Android_AudioPlayer_Exception_Init {
            get {
                return ResourceManager.GetString("Android.AudioPlayer.Exception.Init", resourceCulture);
            }
        }
        
        public static string Android_AudioPlayer_Exception_Reinit {
            get {
                return ResourceManager.GetString("Android.AudioPlayer.Exception.Reinit", resourceCulture);
            }
        }
        
        public static string Android_NativeAGC_Exception_AndroidRecorder {
            get {
                return ResourceManager.GetString("Android.NativeAGC.Exception.AndroidRecorder", resourceCulture);
            }
        }
        
        public static string Android_NativeAGC_Exception_Init {
            get {
                return ResourceManager.GetString("Android.NativeAGC.Exception.Init", resourceCulture);
            }
        }
        
        public static string Android_AudioRecorder_Exception_Capture {
            get {
                return ResourceManager.GetString("Android.AudioRecorder.Exception.Capture", resourceCulture);
            }
        }
        
        public static string Android_NativeDN_Exception_AndroidRecorder {
            get {
                return ResourceManager.GetString("Android.NativeDN.Exception.AndroidRecorder", resourceCulture);
            }
        }
        
        public static string Android_NativeDN_Exception_Init {
            get {
                return ResourceManager.GetString("Android.NativeDN.Exception.Init", resourceCulture);
            }
        }
        
        public static string Android_NativeAEC_Exception_AndroidRecorder {
            get {
                return ResourceManager.GetString("Android.NativeAEC.Exception.AndroidRecorder", resourceCulture);
            }
        }
        
        public static string Android_NativeAEC_Exception_Init {
            get {
                return ResourceManager.GetString("Android.NativeAEC.Exception.Init", resourceCulture);
            }
        }
        
        public static string Settings_Audio_InputDevices {
            get {
                return ResourceManager.GetString("Settings.Audio.InputDevices", resourceCulture);
            }
        }
        
        public static string Settings_Audio_OutputDevices {
            get {
                return ResourceManager.GetString("Settings.Audio.OutputDevices", resourceCulture);
            }
        }
        
        public static string Settings_Audio_Denoisers {
            get {
                return ResourceManager.GetString("Settings.Audio.Denoisers", resourceCulture);
            }
        }
        
        public static string Settings_Audio_AutomaticGainControllers {
            get {
                return ResourceManager.GetString("Settings.Audio.AutomaticGainControllers", resourceCulture);
            }
        }
        
        public static string Settings_Audio_EchoCancelers {
            get {
                return ResourceManager.GetString("Settings.Audio.EchoCancelers", resourceCulture);
            }
        }
        
        public static string Settings_Audio_MicrophoneTest {
            get {
                return ResourceManager.GetString("Settings.Audio.MicrophoneTest", resourceCulture);
            }
        }
        
        public static string Settings_Audio_MicrophoneTest_Test {
            get {
                return ResourceManager.GetString("Settings.Audio.MicrophoneTest.Test", resourceCulture);
            }
        }
        
        public static string Settings_Audio_TestOutput {
            get {
                return ResourceManager.GetString("Settings.Audio.TestOutput", resourceCulture);
            }
        }
        
        public static string AddServer_AddServer {
            get {
                return ResourceManager.GetString("AddServer.AddServer", resourceCulture);
            }
        }
        
        public static string AddServer_Name {
            get {
                return ResourceManager.GetString("AddServer.Name", resourceCulture);
            }
        }
        
        public static string AddServer_IP {
            get {
                return ResourceManager.GetString("AddServer.IP", resourceCulture);
            }
        }
        
        public static string AddServer_Port {
            get {
                return ResourceManager.GetString("AddServer.Port", resourceCulture);
            }
        }
        
        public static string Credits_Author {
            get {
                return ResourceManager.GetString("Credits.Author", resourceCulture);
            }
        }
        
        public static string Credits_Contributors {
            get {
                return ResourceManager.GetString("Credits.Contributors", resourceCulture);
            }
        }
        
        public static string Credits_Version {
            get {
                return ResourceManager.GetString("Credits.Version", resourceCulture);
            }
        }
        
        public static string Credits_AppVersion {
            get {
                return ResourceManager.GetString("Credits.AppVersion", resourceCulture);
            }
        }
        
        public static string Credits_Codec {
            get {
                return ResourceManager.GetString("Credits.Codec", resourceCulture);
            }
        }
        
        public static string Settings_Audio_MicrophoneSensitivity {
            get {
                return ResourceManager.GetString("Settings.Audio.MicrophoneSensitivity", resourceCulture);
            }
        }
        
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
