#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("VoiceCraft.Mobile.Droid.Resource", IsApplication=true)]

namespace VoiceCraft.Mobile.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.2.2.120")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int arrow_right_thick = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int bgdark = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int bglight = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int cog = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int delete = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int exit = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int headphones_off = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int help_box = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int information = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int @lock = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int microphone = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int microphone_off = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int server = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int vc = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int view_channels = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int volume_medium = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_foreground = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
