//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoiceCraft.Client.Assets.Locals {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VoiceCraft.Client.Assets.Locals.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings.General", resourceCulture);
            }
        }
        
        public static string Home_Settings {
            get {
                return ResourceManager.GetString("Home.Settings", resourceCulture);
            }
        }
        
        public static string Home_Servers {
            get {
                return ResourceManager.GetString("Home.Servers", resourceCulture);
            }
        }
        
        public static string Home_Credits {
            get {
                return ResourceManager.GetString("Home.Credits", resourceCulture);
            }
        }
        
        public static string Home_AddServer {
            get {
                return ResourceManager.GetString("Home.AddServer", resourceCulture);
            }
        }
        
        public static string Settings_General_Language {
            get {
                return ResourceManager.GetString("Settings.General.Language", resourceCulture);
            }
        }
        
        public static string Settings_General_Theme {
            get {
                return ResourceManager.GetString("Settings.General.Theme", resourceCulture);
            }
        }
        
        public static string Settings_General_BackgroundImage {
            get {
                return ResourceManager.GetString("Settings.General.BackgroundImage", resourceCulture);
            }
        }
        
        public static string Settings_General_NotificationDismiss {
            get {
                return ResourceManager.GetString("Settings.General.NotificationDismiss", resourceCulture);
            }
        }
        
        public static string Settings_General_HideServerAddresses {
            get {
                return ResourceManager.GetString("Settings.General.HideServerAddresses", resourceCulture);
            }
        }
        
        public static string Settings_General_DisableNotifications {
            get {
                return ResourceManager.GetString("Settings.General.DisableNotifications", resourceCulture);
            }
        }
        
        public static string Settings_Audio {
            get {
                return ResourceManager.GetString("Settings.Audio", resourceCulture);
            }
        }
    }
}
